import { defineConfig } from 'tsdown';

import tailwindcss from '@tailwindcss/postcss';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    TreeSelect: 'src/components/organisms/tree-select.tsx',
    Form: 'src/components/organisms/form/index.ts',
    AutoComplete: 'src/components/atoms/auto-complete.tsx',
    Avatar: 'src/components/atoms/avatar.tsx',
    Badge: 'src/components/atoms/badge.tsx',
    Segmented: 'src/components/atoms/segmented.tsx',
    TimePicker: 'src/components/atoms/time-picker.tsx',
    Typography: 'src/components/atoms/typography/index.ts',
    Button: 'src/components/atoms/button.tsx',
    CodeEditor: 'src/components/atoms/code-editor.tsx',
    Tag: 'src/components/atoms/tag.tsx',
    Card: 'src/components/molecules/card.tsx',
    Descriptions: 'src/components/molecules/descriptions.tsx',
    Timeline: 'src/components/molecules/timeline.tsx',
    Transfer: 'src/components/molecules/transfer.tsx',
    Tour: 'src/components/organisms/tour.tsx',
    Tree: 'src/components/organisms/tree.tsx',
    Rate: 'src/components/atoms/rate.tsx',
    Cascader: 'src/components/atoms/cascader.tsx',
    Alert: 'src/components/molecules/alert.tsx',
    Breadcrumb: 'src/components/molecules/breadcrumb.tsx',
    Steps: 'src/components/molecules/steps.tsx',
    Popconfirm: 'src/components/molecules/popconfirm.tsx',
    Pagination: 'src/components/molecules/pagination.tsx',
    Table: 'src/components/organisms/table.tsx',
    Space: 'src/components/molecules/space.tsx',
    ScrollArea: 'src/components/molecules/scroll-area.tsx',
    Menu: 'src/components/molecules/menu/index.ts',
    Reveals: 'src/components/molecules/reveals/index.ts',
    Layout: 'src/components/templates/layout/index.ts',
    utils: 'src/lib/utils/index.ts',
    providers: 'src/providers/index.ts',
  },
  outDir: 'dist',
  format: ['esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  unbundle: true,
  deps: { onlyBundle: ['gsap'] },
  // tsdown 0.23 owns CSS extraction; a second PostCSS plugin overwrites
  // the emitted stylesheet with a JavaScript placeholder.
  css: {
    transformer: 'postcss',
    splitting: false,
    fileName: 'style.css',
    target: false,
    postcss: { plugins: [tailwindcss()] },
  },
});
